package com.stefang.dev.core.ui

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val green_theme_light_primary = Color(0xFF106D20)
val green_theme_light_onPrimary = Color(0xFFFFFFFF)
val green_theme_light_primaryContainer = Color(0xFF9DF898)
val green_theme_light_onPrimaryContainer = Color(0xFF002204)
val green_theme_light_secondary = Color(0xFF006E1C)
val green_theme_light_onSecondary = Color(0xFFFFFFFF)
val green_theme_light_secondaryContainer = Color(0xFF94F990)
val green_theme_light_onSecondaryContainer = Color(0xFF002204)
val green_theme_light_tertiary = Color(0xFF286C2A)
val green_theme_light_onTertiary = Color(0xFFFFFFFF)
val green_theme_light_tertiaryContainer = Color(0xFFABF5A3)
val green_theme_light_onTertiaryContainer = Color(0xFF002203)
val green_theme_light_error = Color(0xFFBA1A1A)
val green_theme_light_errorContainer = Color(0xFFFFDAD6)
val green_theme_light_onError = Color(0xFFFFFFFF)
val green_theme_light_onErrorContainer = Color(0xFF410002)
val green_theme_light_background = Color(0xFFF5FFF3)
val green_theme_light_onBackground = Color(0xFF00210E)
val green_theme_light_surface = Color(0xFFF5FFF3)
val green_theme_light_onSurface = Color(0xFF00210E)
val green_theme_light_surfaceVariant = Color(0xFFDEE5D8)
val green_theme_light_onSurfaceVariant = Color(0xFF424940)
val green_theme_light_outline = Color(0xFF72796F)
val green_theme_light_inverseOnSurface = Color(0xFFC2FFD0)
val green_theme_light_inverseSurface = Color(0xFF00391C)
val green_theme_light_inversePrimary = Color(0xFF82DB7E)
val green_theme_light_shadow = Color(0xFF000000)
val green_theme_light_surfaceTint = Color(0xFF106D20)
val green_theme_light_outlineVariant = Color(0xFFC2C9BD)
val green_theme_light_scrim = Color(0xFF000000)

val green_theme_dark_primary = Color(0xFF82DB7E)
val green_theme_dark_onPrimary = Color(0xFF00390A)
val green_theme_dark_primaryContainer = Color(0xFF005312)
val green_theme_dark_onPrimaryContainer = Color(0xFF9DF898)
val green_theme_dark_secondary = Color(0xFF78DC77)
val green_theme_dark_onSecondary = Color(0xFF00390A)
val green_theme_dark_secondaryContainer = Color(0xFF005313)
val green_theme_dark_onSecondaryContainer = Color(0xFF94F990)
val green_theme_dark_tertiary = Color(0xFF90D889)
val green_theme_dark_onTertiary = Color(0xFF003909)
val green_theme_dark_tertiaryContainer = Color(0xFF085314)
val green_theme_dark_onTertiaryContainer = Color(0xFFABF5A3)
val green_theme_dark_error = Color(0xFFFFB4AB)
val green_theme_dark_errorContainer = Color(0xFF93000A)
val green_theme_dark_onError = Color(0xFF690005)
val green_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val green_theme_dark_background = Color(0xFF00210E)
val green_theme_dark_onBackground = Color(0xFF99F7B5)
val green_theme_dark_surface = Color(0xFF00210E)
val green_theme_dark_onSurface = Color(0xFF99F7B5)
val green_theme_dark_surfaceVariant = Color(0xFF424940)
val green_theme_dark_onSurfaceVariant = Color(0xFFC2C9BD)
val green_theme_dark_outline = Color(0xFF8C9388)
val green_theme_dark_inverseOnSurface = Color(0xFF00210E)
val green_theme_dark_inverseSurface = Color(0xFF99F7B5)
val green_theme_dark_inversePrimary = Color(0xFF106D20)
val green_theme_dark_shadow = Color(0xFF000000)
val green_theme_dark_surfaceTint = Color(0xFF82DB7E)
val green_theme_dark_outlineVariant = Color(0xFF424940)
val green_theme_dark_scrim = Color(0xFF000000)

val green_seed = Color(0xFF388E3C)

val LightColorsGreen = lightColorScheme(
    primary = green_theme_light_primary,
    onPrimary = green_theme_light_onPrimary,
    primaryContainer = green_theme_light_primaryContainer,
    onPrimaryContainer = green_theme_light_onPrimaryContainer,
    secondary = green_theme_light_secondary,
    onSecondary = green_theme_light_onSecondary,
    secondaryContainer = green_theme_light_secondaryContainer,
    onSecondaryContainer = green_theme_light_onSecondaryContainer,
    tertiary = green_theme_light_tertiary,
    onTertiary = green_theme_light_onTertiary,
    tertiaryContainer = green_theme_light_tertiaryContainer,
    onTertiaryContainer = green_theme_light_onTertiaryContainer,
    error = green_theme_light_error,
    errorContainer = green_theme_light_errorContainer,
    onError = green_theme_light_onError,
    onErrorContainer = green_theme_light_onErrorContainer,
    background = green_theme_light_background,
    onBackground = green_theme_light_onBackground,
    surface = green_theme_light_surface,
    onSurface = green_theme_light_onSurface,
    surfaceVariant = green_theme_light_surfaceVariant,
    onSurfaceVariant = green_theme_light_onSurfaceVariant,
    outline = green_theme_light_outline,
    inverseOnSurface = green_theme_light_inverseOnSurface,
    inverseSurface = green_theme_light_inverseSurface,
    inversePrimary = green_theme_light_inversePrimary,
    surfaceTint = green_theme_light_surfaceTint,
    outlineVariant = green_theme_light_outlineVariant,
    scrim = green_theme_light_scrim,
)

val DarkColorsGreen = darkColorScheme(
    primary = green_theme_dark_primary,
    onPrimary = green_theme_dark_onPrimary,
    primaryContainer = green_theme_dark_primaryContainer,
    onPrimaryContainer = green_theme_dark_onPrimaryContainer,
    secondary = green_theme_dark_secondary,
    onSecondary = green_theme_dark_onSecondary,
    secondaryContainer = green_theme_dark_secondaryContainer,
    onSecondaryContainer = green_theme_dark_onSecondaryContainer,
    tertiary = green_theme_dark_tertiary,
    onTertiary = green_theme_dark_onTertiary,
    tertiaryContainer = green_theme_dark_tertiaryContainer,
    onTertiaryContainer = green_theme_dark_onTertiaryContainer,
    error = green_theme_dark_error,
    errorContainer = green_theme_dark_errorContainer,
    onError = green_theme_dark_onError,
    onErrorContainer = green_theme_dark_onErrorContainer,
    background = green_theme_dark_background,
    onBackground = green_theme_dark_onBackground,
    surface = green_theme_dark_surface,
    onSurface = green_theme_dark_onSurface,
    surfaceVariant = green_theme_dark_surfaceVariant,
    onSurfaceVariant = green_theme_dark_onSurfaceVariant,
    outline = green_theme_dark_outline,
    inverseOnSurface = green_theme_dark_inverseOnSurface,
    inverseSurface = green_theme_dark_inverseSurface,
    inversePrimary = green_theme_dark_inversePrimary,
    surfaceTint = green_theme_dark_surfaceTint,
    outlineVariant = green_theme_dark_outlineVariant,
    scrim = green_theme_dark_scrim,
)
